on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "master"
      - "ci/**"  # launch everytime when ci edit's

permissions:
  contents: read

jobs:

  build-test:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4.1.1

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install poetry
        run: pip install poetry

      - name: install dependencies
        run: poetry install

      - name: test code
        run: poetry run nox
