on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "master"
      - "ci/**"  # launch everytime when ci edit's

permissions:
  contents: read

jobs:

  build-test:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: setup poetry
        uses: iak-it/iak-it-general/.github/actions/poetry-setup.yml
        with:
          python-version: "3.12"

      - name: test code
        run: poetry run nox
