name: Build and publish package
on:
  push:
    branches:
      - "ci/**"
    tags:
      - "v*.*.*"


permissions:
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml

  publish:
    needs:
      - build-test

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: set up environment
        run: >-
          pip install poetry
          poetry install

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: publish package
        run: poetry publish --build -u __token__ -p ${{ steps.mint.outputs.api-token }}
