#name: Build and publish package
#on:
#  push:
#    branches:
#      - "ci/**"
#    tags:
#      - "v*.*.*"
#
#jobs:
#  publish:
#    permissions:
#      contents: read
#      id-token: write
#
#    uses: iak-it/general/.github/workflows/python-poetry-publish.yml@master
#    with:
#      python-version: "3.12"

name: Build and publish package to PyPI
on:
  workflow_call:
    inputs:
      python-version:
        description: "python version"
        type: string
        required: false
        default: "3.12"


permissions:
  contents: read

jobs:
  test-code:
    uses: iak-it/general/.github/workflows/python-poetry-test.yml@master
    with:
      python-version: ${{ inputs.python-version }}

  publish:
    needs:
      - test-code

    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: publish package
        uses: iak-it-actions/python-poetry-publish@v0.0.1
        with:
          python-version: ${{ inputs.python-version }}
