name: Build and publish package
on:
  push:
    branches:
      - "ci/**"
    tags:
      - "v*.*.*"


permissions:
  contents: read

jobs:
  publish:
    uses: iak-it/general/.github/workflows/python-poetry-publish.yml@master
    with:
      python-version: "3.12"
